name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        npm-version:
          - "12.x"
          - "14.x"
          - "15.x"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.npm-version }}"

      - run: yarn install
      - run: grunt jshint
      - run: npm run test

      - name: "Send coverage to codecov.io"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
    env:
      CI: true
